CREATE TABLE VEHICLE(
    REG_NO VARCHAR(5) PRIMARY KEY,
    MODEL VARCHAR(10),
    YEAR INTEGER
);

CREATE TABLE SERVICE_CENTER(
    CENTER_ID VARCHAR(5) PRIMARY KEY,
    CENTER_NAME VARCHAR(10),
    CITY VARCHAR(10)
);

CREATE TABLE SERVICED(
    REG_NO VARCHAR(5),
    CENTER_ID VARCHAR(5),
    SERVICE_DATE DATE,
    COST NUMBER(5),
    FOREIGN KEY(REG_NO) REFERENCES VEHICLE,
    FOREIGN KEY(CENTER_ID) REFERENCES SERVICE_CENTER
);

-- (i) Have been serviced more than twice.
SELECT VEHICLE.* FROM VEHICLE
WHERE VEHICLE.REG_NO IN (SELECT DISTINCT(REG_NO) FROM SERVICED GROUP BY REG_NO HAVING COUNT(REG_NO) >=2);

--(ii) Have a total service cost exceeding ₹20,000. Sort the output by total cost in descending order.

SELECT V.REG_NO, V.MODEL, SUM(S.COST) AS TOTAL_COST
FROM VEHICLE V
JOIN SERVICED S ON V.REG_NO = S.REG_NO
GROUP BY V.REG_NO, V.MODEL
HAVING SUM(S.COST) >= 20000
ORDER BY TOTAL_COST DESC;

-- (iii) Only include vehicles that were serviced at least once in the year 2023.
SELECT VEHICLE.*
FROM VEHICLE
WHERE REG_NO IN (SELECT REG_NO FROM SERVICED WHERE EXTRACT(YEAR FROM SERVICED.SERVICE_DATE)=2023);

--(iv) model starts with the letter 'S' and have a manufacturing year after 2015.
SELECT VEHICLE.*
FROM VEHICLE
WHERE MODEL LIKE 'S%' AND YEAR > 2015;

--(v) Find the names of service centers along with the number of unique vehicles they have serviced in the
-- last 2 years, but only include those centers that have serviced at least 3 different vehicles.

SELECT SERVICE_CENTER.CENTER_NAME,COUNT(DISTINCT(SERVICED.REG_NO)) AS TOTAL_VEHICLES
FROM SERVICED
JOIN SERVICE_CENTER ON SERVICED.CENTER_ID = SERVICE_CENTER.CENTER_ID
WHERE EXTRACT( YEAR FROM SERVICED.SERVICE_DATE) BETWEEN 2023 AND 2025 
GROUP BY SERVICE_CENTER.CENTER_NAME
HAVING COUNT(DISTINCT(REG_NO)) >= 3;

--(vi) Delete the vehicle record whose registation is before 2010
DELETE FROM SERVICED WHERE REG_NO IN(SELECT REG_NO FROM VEHICLE WHERE YEAR < 2010);    -- FOR ATTRIBUTES THAT ARE REFERENCED 
DELETE FROM VEHICLE WHERE YEAR < 2010;                                                 -- CHILD RECORD MUST BE DELETED FIRST

--INSERTED VALUES
-- REM INSERTING into "SYSTEM"."VEHICLE"
-- SET DEFINE OFF;
-- Insert into "SYSTEM"."VEHICLE" (REG_NO,MODEL,YEAR) values ('R01','HONDA',2016);
-- Insert into "SYSTEM"."VEHICLE" (REG_NO,MODEL,YEAR) values ('R02','SUZUKI',2018);
-- Insert into "SYSTEM"."VEHICLE" (REG_NO,MODEL,YEAR) values ('R03','JESKO',2009);
-- Insert into "SYSTEM"."VEHICLE" (REG_NO,MODEL,YEAR) values ('R04','NANO',2010);

-- REM INSERTING into "SYSTEM"."VEHICLE"
-- SET DEFINE OFF;
-- Insert into "SYSTEM"."VEHICLE" (REG_NO,MODEL,YEAR) values ('R01','HONDA',2016);
-- Insert into "SYSTEM"."VEHICLE" (REG_NO,MODEL,YEAR) values ('R02','SUZUKI',2018);
-- Insert into "SYSTEM"."VEHICLE" (REG_NO,MODEL,YEAR) values ('R03','JESKO',2009);
-- Insert into "SYSTEM"."VEHICLE" (REG_NO,MODEL,YEAR) values ('R04','NANO',2010);

-- REM INSERTING into "SYSTEM"."SERVICED"
-- SET DEFINE OFF;
-- Insert into "SYSTEM"."SERVICED" (REG_NO,CENTER_ID,SERVICE_DATE,COST) values ('R01','C01',to_date('11/06/25','DD/MM/RR'),15000);
-- Insert into "SYSTEM"."SERVICED" (REG_NO,CENTER_ID,SERVICE_DATE,COST) values ('R01','C01',to_date('20/05/24','DD/MM/RR'),3000);
-- Insert into "SYSTEM"."SERVICED" (REG_NO,CENTER_ID,SERVICE_DATE,COST) values ('R01','C02',to_date('15/04/23','DD/MM/RR'),10000);
-- Insert into "SYSTEM"."SERVICED" (REG_NO,CENTER_ID,SERVICE_DATE,COST) values ('R02','C02',to_date('10/01/19','DD/MM/RR'),15000);
-- Insert into "SYSTEM"."SERVICED" (REG_NO,CENTER_ID,SERVICE_DATE,COST) values ('R03','C01',to_date('08/10/23','DD/MM/RR'),40000);
-- Insert into "SYSTEM"."SERVICED" (REG_NO,CENTER_ID,SERVICE_DATE,COST) values ('R04','C01',to_date('09/04/24','DD/MM/RR'),10000);
