-- CREATING TABLE
CREATE TABLE ITEM_2 (
    ITEMID VARCHAR(5) PRIMARY KEY,
    INAME VARCHAR(10),
    COLOR VARCHAR(10),
    WEIGHT INTEGER
);

CREATE TABLE SUPPLIER (
    SID VARCHAR(5) PRIMARY KEY,
    SNAME VARCHAR(10),
    CITY VARCHAR(10)
);

CREATE TABLE SUPPLY (
    SID VARCHAR(5) PRIMARY KEY,
    ITEM_ID VARCHAR(10),
    QUANTITY VARCHAR(10),
    PRIMARY KEY (SID,ITEM_ID),
    FOREIGN KEY(SID) REFERENCES SUPPLIER,
    FOREIGN KEY(ITEM_ID) REFERENCES ITEM_2
);

--(i) INSERTING DATA
REM INSERTING into "SYSTEM"."SUPPLIER"
SET DEFINE OFF;
Insert into "SYSTEM"."SUPPLIER" (SID,SNAME,CITY) values ('S1','Supplier1','Delhi');
Insert into "SYSTEM"."SUPPLIER" (SID,SNAME,CITY) values ('S2','Supplier2','Calcutta');
Insert into "SYSTEM"."SUPPLIER" (SID,SNAME,CITY) values ('S3','Supplier3','Mumbai');
Insert into "SYSTEM"."SUPPLIER" (SID,SNAME,CITY) values ('S4','Supplier4','Delhi');
Insert into "SYSTEM"."SUPPLIER" (SID,SNAME,CITY) values ('S5','Supplier5','Chennai');
Insert into "SYSTEM"."SUPPLIER" (SID,SNAME,CITY) values ('S6','Supplier6','Mumbai');

REM INSERTING into "SYSTEM"."SUPPLY"
SET DEFINE OFF;
Insert into "SYSTEM"."SUPPLY" (SID,ITEM_ID,QUANTITY) values ('S1','ITEM1',300);
Insert into "SYSTEM"."SUPPLY" (SID,ITEM_ID,QUANTITY) values ('S2','ITEM2',200);
Insert into "SYSTEM"."SUPPLY" (SID,ITEM_ID,QUANTITY) values ('S3','ITEM3',150);
Insert into "SYSTEM"."SUPPLY" (SID,ITEM_ID,QUANTITY) values ('S4','ITEM1',100);
Insert into "SYSTEM"."SUPPLY" (SID,ITEM_ID,QUANTITY) values ('S4','ITEM2',250);
Insert into "SYSTEM"."SUPPLY" (SID,ITEM_ID,QUANTITY) values ('S5','ITEM4',500);

REM INSERTING into "SYSTEM"."ITEM_2"
SET DEFINE OFF;
Insert into "SYSTEM"."ITEM_2" (ITEMID,INAME,COLOR,WEIGHT) values ('I2','ITEM2','BLUE',30);
Insert into "SYSTEM"."ITEM_2" (ITEMID,INAME,COLOR,WEIGHT) values ('I3','ITEM3','GREEN',20);
Insert into "SYSTEM"."ITEM_2" (ITEMID,INAME,COLOR,WEIGHT) values ('I4','ITEM1','RED',40);
Insert into "SYSTEM"."ITEM_2" (ITEMID,INAME,COLOR,WEIGHT) values ('I5','ITEM2','YELLOW',10);
Insert into "SYSTEM"."ITEM_2" (ITEMID,INAME,COLOR,WEIGHT) values ('I1','ITEM1','RED',50);

--(ii)
SELECT * FROM SUPPLIER;

--(iii)
SELECT DISTINCT ITEM_2.ITEMID , ITEM_2.INAME 
FROM SUPPLY, ITEM_2
WHERE ITEM_2.ITEMID IN (SELECT ITEM_ID FROM SUPPLY);

--(iv)
SELECT * FROM SUPPLIER 
WHERE CITY= 'Delhi';

--(v)
SELECT * FROM SUPPLIER 
WHERE CITY != 'Calcutta';

--(vi)
-- (Method-1)
SELECT DISTINCT ITEM_2.ITEMID , ITEM_2.INAME 
FROM SUPPLY, ITEM_2
WHERE ITEM_2.ITEMID NOT IN (SELECT ITEM_ID FROM SUPPLY);
--(Method-2)
SELECT * FROM SUPPLIER
WHERE SID NOT IN (SELECT SID FROM SUPPLY);

--(vii)
--(Method-1)
SELECT DISTINCT SUPPLIER.*
FROM SUPPLIER, SUPPLY 
WHERE SUPPLIER.SID IN (SELECT DISTINCT SID FROM SUPPLY);
--(Method-2)
SELECT DISTINCT SUPPLY.SID, SUPPLIER.SNAME 
FROM SUPPLY, SUPPLIER
WHERE SUPPLY.SID = SUPPLIER.SID;

--(viii)
SELECT SUPPLIER.* 
FROM SUPPLIER, SUPPLY
WHERE SUPPLIER.SID = SUPPLY.SID AND SUPPLY.ITEM_ID = 'I1';

--(ix)
SELECT DISTINCT SUPPLIER.* 
FROM SUPPLIER, SUPPLY
WHERE SUPPLIER.SID = SUPPLY.SID 
AND SUPPLY.SID IN (SELECT SID FROM SUPPLY WHERE ITEM_ID='I1') 
AND SUPPLIER.SID IN (SELECT SID FROM SUPPLY WHERE ITEM_ID='I2');

--(x)
SELECT DISTINCT SUPPLIER.* 
FROM SUPPLIER, SUPPLY
WHERE SUPPLIER.SID IN (SELECT SID FROM SUPPLY WHERE ITEM_ID='I1' OR ITEM_ID='I2');

--(xi)
SELECT SNAME, INAME
FROM SUPPLIER
NATURAL JOIN SUPPLY
INNER JOIN ITEM_2 ON SUPPLY.ITEM_ID = ITEM_2.ITEMID
WHERE COLOR='RED';

--(Xii)
SELECT SUPPLIER.SNAME
FROM SUPPLIER,SUPPLY,ITEM_2
WHERE SUPPLIER.SID = SUPPLY.SID AND SUPPLY.ITEM_ID= ITEM_2.ITEMID
AND ITEM_2.COLOR = 'RED' AND QUANTITY BETWEEN 200 AND 500;

--(xiii)
SELECT ITEM_2.*
FROM ITEM_2
WHERE ITEM_2.ITEMID IN (SELECT ITEM_ID AS TOTAL 
                        FROM SUPPLY 
                        GROUP BY ITEM_ID 
                        HAVING COUNT(ITEM_ID) >=2);

--(xiv)
SELECT SUPPLIER.SNAME FROM SUPPLIER 
WHERE SUPPLIER.SID IN
(SELECT SID FROM SUPPLY
GROUP BY SID
HAVING COUNT(SID) = (SELECT COUNT(*) FROM ITEM));

--(XV)
SELECT SID,SNAME, ITEM_ID, QUANTITY AS MAX_QUANTITY
FROM SUPPLY S
NATURAL JOIN SUPPLIER
WHERE QUANTITY = (
    SELECT MAX(QUANTITY)
    FROM SUPPLY
    WHERE ITEM_ID = S.ITEM_ID
);
